# These are supported funding model platforms

# GitHub Sponsors (uncomment when ready)
# github: [ssfdre38]

# Other platforms (uncomment and add usernames when ready)
# patreon: username
# open_collective: project-name
# ko_fi: username
# liberapay: username
# custom: ['https://yourwebsite.com/donate']

# Note: This project is free and open source.
# Donations are appreciated but never required.
# Our mission is to make security accessible to everyone!
